name: cappuchino_prototype
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  # Provider for state management
  provider: ^6.1.2
  go_router: ^14.6.2
  # Functional programming
  dartz: ^0.10.1
  # Equatable for value equality
  equatable: ^2.0.7

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
